### ISSUE TITLE
SOFT1.0 and S2Kit10 lib lost

### ISSUE THREAD

**Issue by jessychen1016** [machc/spherical_embeddings#1]
Hi,

Thank you for your wonderful work! I am now trying to calculate SO3 rotations between two spheres, and I found this code helping! However, the SOFT1.0 and S2Kit10 and their links are no longer available. Could you please provide an archive package containing SOFT1.0 and S2Kit10?

Thanks in advance!

**Comment by machc** [comment]
Hi, thanks for raising this! Luckily, the libraries are cached on archive.org. I updated the links on the README; here are direct download links: [SOFT 1.0](https://web.archive.org/web/20070214112805/http://www.cs.dartmouth.edu/~geelong/soft/soft-1.0.tar.gz
), [S2Kit](https://web.archive.org/web/20150926234341/http://www.cs.dartmouth.edu/~geelong/sphere/s2kit10.tar.gz).
